### ISSUE TITLE
Cannot route external traffic (helm)

### ISSUE THREAD

**Issue by nox-404** [Place1/wg-access-server#136]
Hello,
I can't get any traffic aside from the peer to the server to work
Any idea ?

My goal is to get the peers to connect to the node's network and also route all traffic through that node (DNS included)

Here are my helm values:

```
# wg-access-server config
config:
  externalHost: host
  storage: mysql://user:password@mariadb.namespace.svc.cluster.local:3306/database?parseTime=true
  vpn:
    cidr: x.x.x.0/24
    allowedIPs:
      - 0.0.0.0/0
      - ::/0
  dns:
    upstream:
      - resolveconf

web:
  config:
    adminUsername: admin
    adminPassword: password

  service:
    type: ClusterIP

wireguard:
  config:
    privateKey: private-key
  service:
    type: NodePort

persistence:
  enabled: false

ingress:
  enabled: true
  hosts:
  - host
  tls:
    - secretName: host-tls
      hosts:
        - host

nameOverride: wireguard
fullnameOverride: wireguard
```

Just one note though, I'm using an image with the following fix #135 as I'm using a mariadb storage
