### ISSUE TITLE
OIDC Azure issue

### ISSUE THREAD

**Issue by MaksymBilenko** [Place1/wg-access-server#186]
Hello,
I'm having this config
```
...
      scopes:
        - openid
        - email
        - profile
      claimMapping:
        admin: "'WireguardAdmins' in group_membership"
```

Also WireguardAdmins group in my OIDC provider (Azure). When I'm tring ti sign in - I'm getting that error:
`No parameter 'group_membership' found.`
