### ISSUE TITLE
How to avoid wireguard docker NAT and masquerading issues

### ISSUE THREAD

**Issue by KimchaC** [Place1/wg-access-server#26]
This is not really a feature request, but something I struggled with and I think other people may too. So I wanted to document the solution here and it can be closed right away.

By default docker places containers (including wg-access-server) in it's own network like 172.28.0.0/16 and then uses NAT and masquerading to route the traffic into the internal network.

Let's say the wg-access-server container has the IP 172.28.0.8. All traffic coming from it to the host's network will seem to come from the docker0 IP 172.28.0.1.

What it means for wg-access-server is that all connections from the VPN clients will also appear to come from 172.28.0.1 instead of from their VPN IP (like 10.44.0.3).

You can test this by running `nc -kvl 5060` on one of the servers in the host network and then connecting from a VPN client to it using telnet <internal ip> 5060. It will show 172.28.0.1 as the originator.

The only way I could find to solve this issue was by running the container in network-mode: host.

I did this by adding this to my docker-compose.yml:
```
version: "3.7"
services:
  wg-access-server:
    [...]
    network_mode: "host"
```

If you already have a wireguard interface on the host you also need to change the interface in the config.yaml:
```
wireguard:
  # The network interface name for wireguard
  # Optional
  interfaceName: wg1
```

After making that change connections from VPN clients come from their IPs in the VPN network.

I am using traefik as my reverse proxy in front of docker services and this made it impossible to use the automatic discovery. So I added a file provider with the following config:
```
# Traefik can't route to containers running in host network mode.
# So we use this config to define it.

http:
  routers:
    vpn:
      service: vpn_service
      rule: "Host(`vpn.example.com`)"

  services:
    vpn_service:
      loadBalancer:
        servers:
          - url: http://172.17.0.1:8000
```

Another thing that was particular to my own setup is that I am running internal services on the same host. I wanted them to be accessible from both the internet and from the VPN. When access from the VPN they should either request a login or show a "Connect to VPN to access message". And when accessed from within the VPN they should be allowed without an additional login.

I was able to achieve this by adding the server's external IP to my wireguard AllowedIPs config, such as:
```
AllowedIPs = 10.44.0.0/16, 10.0.0.0/16, 35.233.XX.XX/32
```

But since now all connections to 35.233.XX.XX were routed through the internet of the VPN server all the logs showed that the traffic came also from the external IP 35.233.XX.XX (VPN and services are on the same server in my case).

I was able to solve this by changing requests to that IP to the IP of the traefik container:
```
sudo iptables -t nat -A PREROUTING -p tcp -d 35.233.XX.XX --dport 443 -i wg1 -j DNAT --to 172.28.0.6:443
```

Now when a VPN client tries to connect to service.example.com:443 their request is redirected from  35.233.XX.XX:443 to 172.28.0.6:443 and the logs show the connection coming from the user's VPN IP (like 10.44.0.3).

Hopefully this can save someone some time.
