### ISSUE TITLE
Incorrect generation of server public key

### ISSUE THREAD

**Issue by mnil** [Place1/wg-access-server#58]
The client key generates to AAA...AA= but after the QR code is gone, the public key is not AAA...AA=.
![image](https://user-images.githubusercontent.com/28663095/86720765-a1da9080-c025-11ea-8c59-1ef87048bc56.png)

My docker-compose
```
  wg-access-server:
    image: place1/wg-access-server
    container_name: wg-access-server
    environment:
      - ADMIN_USER=
      - ADMIN_PASSWORD=
    cap_add:
      - NET_ADMIN
    volumes:
      - "./wg-access-server/data:/data"
      - "./wg-access-server/config.yaml:/config.yaml"
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
```
```
loglevel: info
disableMetadata: false
port: 8000
storage: "file:///data/"
wireguard:
  interfaceName: wgserver
  privateKey: "<...>="
  externalHost: ""
  port: 51820
vpn:
  cidr: "10.45.0.0/24"
  gatewayInterface: "eno1"
  allowedIPs:
    - "0.0.0.0/0"
dns:
  enabled: true
  upstream:  
    - "1.1.1.1"
auth:
  basic:
    users: ["user:pass"]
```
