### ISSUE TITLE
Docker fails to load with error: open /config.yaml: no such file or directory

### ISSUE THREAD

**Issue by robflate** [Place1/wg-access-server#75]
The `:latest` tag gives the error;

`wg-access-server: error: open /config.yaml: no such file or directory, try --help`

and fails to start. The `0.2.5` tag works fine. My docker-compose file is;

```
  wg-access-server:
    image: place1/wg-access-server:latest
    container_name: wg-access-server
    restart: unless-stopped
    networks:
      - t2_proxy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      # - "$WIREGUARD_PORT:8000/tcp"
      - "$WIREGUARD_UDP_PORT:51820/udp"
    volumes:
      - $CONFIG/wg-access-server/data:/data
      # - $CONFIG/wg-access-server/config.yaml:/config.yaml # if you have a custom config file
    environment:
      WIREGUARD_PRIVATE_KEY: $WIREGUARD_PRIVATE_KEY
      ADMIN_USERNAME: $WIREGUARD_ADMIN_USERNAME
      ADMIN_PASSWORD: $WIREGUARD_ADMIN_PASSWORD
      LOG_LEVEL: debug
    devices:
      - /dev/net/tun
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.wireguard-as-rtr.entrypoints=https"
      - "traefik.http.routers.wireguard-as-rtr.rule=Host(`vpn.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.wireguard-as-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.wireguard-as-rtr.service=wireguard-as-svc"
      - "traefik.http.services.wireguard-as-svc.loadbalancer.server.port=8000"
```
