### ISSUE TITLE
Failed to send handshake initiation on v0.3.0. Works on v0.2.5

### ISSUE THREAD

**Issue by robflate** [Place1/wg-access-server#85]
Is there any reason why the following v0.3.0 compose file fails with the client showing `Failed to send handshake initiation write ipd4 0.0.0.0:62400->x.x.x.x:51820: sendto: network is unreachable`. Note: the `config.yaml` file is empty and the container itself starts with no errors;

```
  wg-access-server:
    image: place1/wg-access-server:latest
    container_name: wg-access-server
    restart: unless-stopped
    networks:
      - t2_proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "51820:51820/udp"
    volumes:
      - $CONFIG/wg-access-server/data:/data
      - $CONFIG/wg-access-server/config.yaml:/config.yaml
    environment:
      WG_WIREGUARD_PRIVATE_KEY: $WIREGUARD_PRIVATE_KEY
      WG_ADMIN_USERNAME: $WIREGUARD_ADMIN_USERNAME
      WG_ADMIN_PASSWORD: $WIREGUARD_ADMIN_PASSWORD
      WG_EXTERNAL_HOST: "vpn.$DOMAINNAME"
      WG_CONFIG: debug
    devices:
      - /dev/net/tun
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard-as-rtr.entrypoints=https"
      - "traefik.http.routers.wireguard-as-rtr.rule=Host(`vpn.$DOMAINNAME`)"
      - "traefik.http.routers.wireguard-as-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.wireguard-as-rtr.service=wireguard-as-svc"
      - "traefik.http.services.wireguard-as-svc.loadbalancer.server.port=8000"
```

The following 0.2.5 works fine;

```
  wg-access-server:
    image: place1/wg-access-server:0.2.5
    container_name: wg-access-server
    restart: unless-stopped
    networks:
      - t2_proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "51820:51820/udp"
    volumes:
      - $CONFIG/wg-access-server/data:/data
    environment:
      WIREGUARD_PRIVATE_KEY: $WIREGUARD_PRIVATE_KEY
      ADMIN_USERNAME: $WIREGUARD_ADMIN_USERNAME
      ADMIN_PASSWORD: $WIREGUARD_ADMIN_PASSWORD
      EXTERNAL_HOST: "vpn.$DOMAINNAME"
      CONFIG: info
    devices:
      - /dev/net/tun
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard-as-rtr.entrypoints=https"
      - "traefik.http.routers.wireguard-as-rtr.rule=Host(`vpn.$DOMAINNAME`)"
      - "traefik.http.routers.wireguard-as-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.wireguard-as-rtr.service=wireguard-as-svc"
      - "traefik.http.services.wireguard-as-svc.loadbalancer.server.port=8000"
```

**Comment by michael-robbins** [comment]
I have an incredibly similar setup to yours bar I use a config file, I'm on 0.3 and it seems to be working just fine...

What is your end device? What are the routes it's using (and the client config in general)?

**Comment by zifeo** [comment]
@michael-robbins @robflate I can reproduce on latest docker/docker-compose on Debian 10. Blocked by #74 on 0.2.5 as well.

**Comment by Place1** [comment]
hmm, the environment variable `WG_CONFIG: debug` looks like it's not right. That variable defines the path to a config file if you want to use one. _Probably not your bug though_. If you want to configure the log level you can do it with `LOG_LEVEL=debug`

It seems like your network may be the issue here; but given you says 0.2.5 works (assuming the network hasn't changed) then i'm not sure what the issue could be without more information like some debug logs showing a particular error.

**Comment by zifeo** [comment]
@Place1 Happy to help, loglevel debug does not give any information (except from devices listing and SQL queries). What kind of log should I expect?

```
loglevel: debug

adminUsername: removed
adminPassword: "removed"

port: 8000
externalHost: removed

wireguard:
  enabled: true
  privateKey: removed
  interface: wg0
  port: 51820

vpn:
  cidr: 10.44.0.0/24
  gatewayInterface: ""
  allowedIPs:
    - removed/32 # specific IP

disableMetadata: false
storage: postgres://removed?sslmode=disable

dns:
  enabled: false
  upstream:
    - "8.8.8.8"

auth:
  gitlab:
    name: "Gitlab"
    baseURL: removed
    clientID: removed
    clientSecret: removed
    redirectURL: removed
    emailDomains: removed
```

```
version: "3.7"

networks:
  front:
    external:
      name: removed

volumes:
  postgres:

services:

  wg-access-server:
    image: place1/wg-access-server:0.2.5
    #image: place1/wg-access-server:v0.3.0
    cap_add:
      - NET_ADMIN
    volumes:
      - "./config.yaml:/config.yaml"
    ports:
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      - db
    networks:
      - front
      - default
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:removed
      - traefik.port=8000
      - traefik.docker.network=front
      - traefik.frontend.redirect.entryPoint=https # this is traffic version 1 still but should not be relevant

  db:
    image: postgres:13
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=removed
      - POSTGRES_PASSWORD=removed
      - POSTGRES_USER=removed
      - POSTGRES_DB=removed
```
