### ISSUE TITLE
Access to local host services

### ISSUE THREAD

**Issue by gmag11** [Place1/wg-access-server#94]
Hello. I'm trying to setup WG to acces my VPS apdministration services but I want to use it as a regular VPN to connect to Internet from a different location.

I have this config:

```
version: "3.7"
services:
  wg-access-server:
    image: place1/wg-access-server
    container_name: wg-access-server
    restart: unless-stopped
#    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-data:/data"
      - "./config.yaml:/config.yaml" # if you have a custom config file
    environment:
      - "WG_ADMIN_USERNAME=xxx"
      - "WG_ADMIN_PASSWORD=XXX"
      - "WG_WIREGUARD_PRIVATE_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxx"
      - "WG_STORAGE=sqlite3://data/db.sqlite3"
      - "WG_EXTERNAL_HOST=xxxx.xxxx.com"
      - "WG_VPN_CIDR=192.168.11.0/24"
      - "WG_VPN_ALLOWED_IPS=0.0.0.0/0"
      - "WG_DNS_UPSTREAM=1.1.1.1"
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"

# shared volumes with the host
volumes:
  wg-access-server-data:
    driver: local
```

If I use bridge network I can access Internet but cannot reach local services.

Opposite, if I use host network I can access local services using ethernet interface IP address but route to Internet is blocked.

What could I test to identify the problem? Anyone has this working?

Regards
