### ISSUE TITLE
Google as OIDC provider

### ISSUE THREAD

**Issue by phillip-strefling** [Place1/wg-access-server#95]
I'm attempting to use Google as our OIDC provider and I'm having a hard time getting it to work. I'm getting the following error in my browser:

`server error
trace = 09950d64-d4ac-48e5-a7f2-66eba2641060`

With loglevel set to debug I see no errors in the console.

My config.yaml:
```
wireguard:
  privateKey: "xxx"
dns:
  upstream:
    - "8.8.8.8"
auth:
  # HTTP Basic Authentication
#  basic:
    # Users is a list of htpasswd encoded username:password pairs
    # supports BCrypt, Sha, Ssha, Md5
    # You can create a user using "htpasswd -nB <username>"
#    users: []
  oidc:
    # A name for the backend (can be anything you want)
    name: "Google"
    # Should point to the OIDC Issuer (excluding /.well-known/openid-configuration)
    issuer: "https://accounts.google.com"
    # Your OIDC client credentials which would be provided by your OIDC provider
    clientID: "xxx.apps.googleusercontent.com"
    clientSecret: "xxx"
    # List of scopes to request defaults to ["openid"]
    scopes:
      - openid
    # The full redirect URL
    # The path can be almost anything as long as it doesn't
    # conflict with a path that the web UI uses.
    # /callback is recommended.
    redirectURL: "https://vpn.example.com/callback"
    # You can optionally restrict access to users with an email address
    # that matches an allowed domain.
    # If empty or omitted then all email domains will be allowed.
#    emailDomains:
#      - example.com
    # This is an advanced feature that allows you to define
    # OIDC claim mapping expressions.
    # This feature is used to define wg-access-server admins
    # based off a claim in your OIDC token
    # See https://github.com/Knetic/govaluate/blob/9aa49832a739dcd78a5542ff189fb82c3e423116/MANUAL.md for how to write rules
#    claimMapping:
#      admin: "'Admins' in group_membership"
```

```
My docker-compose.yaml:

version: "3.0"
networks:
  proxy:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./letsencrypt/certs:/etc/nginx/certs"
      - "./letsencrypt/vhost-d:/etc/nginx/vhost.d"
      - "./letsencrypt/html:/usr/share/nginx/html"

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-proxy
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt/certs:/etc/nginx/certs"
      - "./letsencrypt/vhost-d:/etc/nginx/vhost.d"
      - "./letsencrypt/html:/usr/share/nginx/html"
    environment:
      DEFAULT_EMAIL: "admin@example.com"
      NGINX_PROXY_CONTAINER: "nginx-proxy"

  wg-access-server:
    image: place1/wg-access-server
    container_name: wg-access-server
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - "./wireguard/data:/data"
      - "./wireguard/config.yaml:/config.yaml"
    ports:
      #- "8000:8000/tcp"
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      VIRTUAL_HOST: "vpn.example.com"
      LETSENCRYPT_HOST: "vpn.example.com"
      VIRTUAL_PORT: "8000"
      VIRTUAL_PROTO: "http"
      WG_ADMIN_USERNAME: admin
      WG_ADMIN_PASSWORD: ${WG_ADMIN_PASSWORD}
      WG_EXTERNAL_HOST: "https://vpn.example.com"
      WG_PORT: "8000"
      WG_STORAGE: "sqlite3:///data/db.sqlite3"
      WG_WIREGUARD_INTERFACE: "wg1"
      WG_WIREGUARD_PORT: "51820"
      WG_VPN_CIDR: "10.44.0.0/24"
      WG_VPN_GATEWAY_INTERFACE: "eth0"
      WG_VPN_ALLOWED_IPS: "10.44.0.0/24, 10.XX.XX.0/24"
      WG_DNS_ENABLED: "true"
      WG_DNS_UPSTREAM: "1.1.1.1" 
#      WG_WIREGUARD_PRIVATE_KEY: ${WG_WIREGUARD_PRIVATE_KEY}
```
